export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USERNAME_EXISTS: 'USERNAME_EXISTS',
  USER_INVALID_CREDENTIALS: 'USER_INVALID_CREDENTIALS',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  ORDER_PACKAGE_NOT_FOUND: 'ORDER_PACKAGE_NOT_FOUND',
  ORDER_ATTRIBUTION_INVALID: 'ORDER_ATTRIBUTION_INVALID',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_WINNER_INVALID: 'ORDER_WINNER_INVALID',
  ORDER_STATUS_INVALID: 'ORDER_STATUS_INVALID',
  FORBIDDEN: 'FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
