import type { MarketCommandCenterData } from '@/types/market-command-center';

export const marketCommandCenterData: MarketCommandCenterData = {
  marketScore: 78,
  metrics: [
    { label: 'Trend', value: 72, tone: 'primary' },
    { label: 'Likidite', value: 81, tone: 'success' },
    { label: 'Makro Destek', value: 69, tone: 'warning' },
    { label: 'Kurulum Kalitesi', value: 76, tone: 'primary' },
    { label: 'Risk', value: 44, tone: 'danger' },
    { label: 'AI Confidence', value: 84, tone: 'success' },
  ],
  decision: {
    isTradableNow: true,
    strongestScenario: 'XAUUSD 4062 ustunde tutunursa London - NY gecisinde momentum alimi.',
    invalidationLevel: '4048 asagi hacimli kirilim',
    expectedTarget: '4074 - 4082 bolgesi',
  },
  timeline: [
    { time: '07:00', title: 'Asya Seansi', subtitle: 'Likidite hazirlama', importance: 2 },
    { time: '09:00', title: 'London Acilisi', subtitle: 'Yon arayisi', importance: 4 },
    { time: '11:00', title: 'Likidite Taramasi', subtitle: 'Stop hunt olasiligi', importance: 4 },
    { time: '13:30', title: 'Bekleme Alani', subtitle: 'Pozisyon kucultme', importance: 2 },
    { time: '15:30', title: 'ABD Verileri', subtitle: 'Volatilite piki', importance: 5 },
    { time: '16:00', title: 'New York Acilisi', subtitle: 'Ana yon teyidi', importance: 5 },
    { time: '17:00', title: 'Fed Konusmasi', subtitle: 'Makro ton degisimi riski', importance: 5 },
    { time: '20:00', title: 'ABD Kapanisi', subtitle: 'Gun sonu dengeleme', importance: 3 },
  ],
  criticalEvents: [
    {
      time: '15:30',
      currency: 'USD',
      title: 'Non Farm Payroll',
      impact: 5,
      forecast: '190K',
      previous: '206K',
      aiCommentary: 'Altin icin yuksek volatilite bekleniyor, spread genisleyebilir.',
    },
    {
      time: '17:00',
      currency: 'USD',
      title: 'Fed Uyesi Konusmasi',
      impact: 4,
      forecast: 'Sahin ton korunabilir',
      previous: 'Notr',
      aiCommentary: 'DXY guclenirse XAUUSD yukari denemeleri zayiflayabilir.',
    },
    {
      time: '18:30',
      currency: 'USD',
      title: 'Ham Petrol Stoklari',
      impact: 3,
      forecast: '-1.1M',
      previous: '-0.6M',
      aiCommentary: 'Enflasyon algisini etkileyerek tahvil getirilerini oynatabilir.',
    },
  ],
  sessions: [
    { name: 'Sydney', open: '00:00', close: '09:00' },
    { name: 'Tokyo', open: '02:00', close: '11:00' },
    { name: 'London', open: '10:00', close: '19:00' },
    { name: 'New York', open: '15:00', close: '24:00' },
  ],
  goldFocus: {
    bias: 'Bullish',
    premiumDiscount: 'Discount bolgesinden premiuma gecis denemesi',
    liquidity: '4052 alti buyside/sellside dengesizligi temizlendi',
    orderBlock: '4049 - 4053 bullish order block',
    fvg: '4058 - 4061 arasinda one cikan FVG',
    mss: 'M15 yukari MSS teyidi alindi',
    scenario: '4062 ustunde kalicilik ile 4074 test olasiligi yuksek.',
    aiCommentary: '15:30 oncesi agresif pozisyon yerine teyitli kirilim beklenmeli.',
    criticalHours: ['10:00', '11:00', '15:30', '16:00', '17:00'],
    support: ['4053', '4048', '4039'],
    resistance: ['4068', '4074', '4082'],
    volatility: 'High',
  },
  dollarFocus: {
    dxy: '104.22 (+0.18%)',
    us10y: '4.28% (+0.04)',
    fedTone: 'Temkinli sahin',
    macroNews: 'Is gucu verisi beklenti ustu gelirse dolar ivmelenebilir.',
    aiCommentary: 'DXY guclu kalirsa altinda geri cekilme alani genisler.',
    goldImpact: 'Negatif korelasyon guclu, spike sonrasi fake move riski var.',
  },
  coachMessages: [
    'Su an yeni pozisyon acmak icin ideal pencere degil; 15:30 veri oncesi risk yuksek.',
    '4062 ustunde hacimli kapanis gorulmeden trend kovalamak yerine sabirli ol.',
    'Likidite sweep ve MSS birlikte gelirse giris kalitesi artar.',
  ],
  newsFeed: [
    { source: 'FinancialJuice', headline: 'US labor participation ratio surprises slightly higher.', time: '14:52', impact: 'medium' },
    { source: 'Bloomberg', headline: 'Treasury yields edge up before labor data release.', time: '14:49', impact: 'high' },
    { source: 'ForexFactory', headline: 'Fed speaker hints rates may stay restrictive longer.', time: '14:44', impact: 'high' },
    { source: 'TradingEconomics', headline: 'Eurozone PMI revised marginally lower.', time: '14:37', impact: 'low' },
  ],
  defaultRiskChecklist: [
    'Stop ayarlandi mi?',
    'Risk %1 altinda mi?',
    'Haber takvimi kontrol edildi mi?',
    'MSS olustu mu?',
    'FVG olustu mu?',
    'Liquidity Sweep olustu mu?',
    'Spread uygun mu?',
  ],
  opportunities: [
    { symbol: 'XAUUSD', side: 'BUY', confidence: 74, target: '4074', stop: '4048', risk: '0.8%', reward: '1:2.6' },
    { symbol: 'EURUSD', side: 'SELL', confidence: 69, target: '1.0838', stop: '1.0904', risk: '0.7%', reward: '1:2.1' },
    { symbol: 'NASDAQ', side: 'BUY', confidence: 81, target: '20140', stop: '19880', risk: '0.9%', reward: '1:2.8' },
  ],
  liveCommentary: [
    'London acildi, ilk 20 dakikada fake move olasiligi yuksek.',
    'Likidite 4056 civarinda birikiyor.',
    'DXY yukari egimini koruyor.',
    'Altin 4062 etrafinda karar asamasinda.',
    '15:30 yaklasirken yeni pozisyon boyutu azaltilmali.',
  ],
};
